title: Industry Blueprints
description: Industry Blueprints
url: "https://industry-blueprints.github.io"
baseurl: ""
lang: en

author:
  name: Jeremy Hofmann
  site: "https://hofmann-studio.github.io"

repository:
  site: "https://github.com/industry-blueprints/industry-blueprints.github.io"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  capabilities:
    output: true
    permalink: /capabilities/:name/

defaults:
  - scope:
      path: ""
      type: capabilities
    values:
      layout: capability

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .design
